Repository The-OpenROAD-Project/OpenROAD, pull requests merged in 2024-08, with the labels that each got.

#5620 gui: Issue an error instead of crashing when loading a drc file without a database opened.
  src/gui/src/drcWidget.cpp
Labels: gui

#5641 etc: move unzip dependency
  etc/DependencyInstaller.sh
Labels: dependencies

#4159 [Docs] OR Review 2
  .gitignore
  docs/conf.py
  docs/index.md
  docs/requirements.txt
  docs/revert-links.py
  docs/toc.yml
  docs/user/Build.md
  src/README.md
Labels: documentation
